- hosts: all
  tasks:
    - name: "Install apt-transport-https"
      apt:
        name: ['apt-transport-https']
        state: latest
    - name: "Install ca-certificatess"
      apt:
        name: ['ca-certificates']
        state: latest
    - name: "Install curl"
      apt:
        name: ['curl']
        state: latest
    - name: "Install software-properties-common"
      apt:
        name: ['software-properties-common']
        state: latest
        
    - name: "Get GPG"
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      
    - name: "Add Docker Repository"
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      
    - name: "Update packages"
      apt:
        update_cache: yes
        
    - name: "Install Docker"
      apt:
          name: ['docker-ce']
          state: latest
     
    - name: "Obtain Jenkins keyring"
      shell: curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
      
    - name: "Add keyring"
      shell: echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
          
    - name: "Update and install jenkins"
      shell: sudo apt-get update && install jenkins
